# Generated by Django 4.2.16 on 2026-04-16 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_add_certificate_pem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="certificate_pem",
        ),
    ]
