# Generated by Django 4.2.16 on 2026-04-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_remove_userprofile_certificate_pem"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="certificate_pem",
            field=models.TextField(blank=True, default=""),
        ),
    ]
