# Generated by Django 4.2.16 on 2026-05-07 15:00

import base64
import hashlib
from datetime import datetime, timedelta

from cryptography import x509
from cryptography.fernet import Fernet
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.x509.oid import NameOID
from django.conf import settings
from django.db import migrations, models


def _fernet() -> Fernet:
    env_key = (getattr(settings, "PRIVATE_KEY_FERNET_KEY", "") or "").strip()
    if env_key:
        return Fernet(env_key.encode("utf-8"))
    derived = hashlib.sha256(settings.SECRET_KEY.encode("utf-8")).digest()
    return Fernet(base64.urlsafe_b64encode(derived))


def _create_self_signed_user_certificate(private_key_pem: str, username: str) -> str:
    private_key = serialization.load_pem_private_key(
        private_key_pem.encode("utf-8"),
        password=None,
    )
    public_key = private_key.public_key()

    subject = issuer = x509.Name(
        [
            x509.NameAttribute(NameOID.COUNTRY_NAME, "IN"),
            x509.NameAttribute(
                NameOID.ORGANIZATION_NAME, "NIC Digital Signature System"
            ),
            x509.NameAttribute(NameOID.COMMON_NAME, username),
        ]
    )

    cert = (
        x509.CertificateBuilder()
        .subject_name(subject)
        .issuer_name(issuer)
        .public_key(public_key)
        .serial_number(x509.random_serial_number())
        .not_valid_before(datetime.utcnow())
        .not_valid_after(datetime.utcnow() + timedelta(days=365))
        .sign(private_key, hashes.SHA256())
    )
    return cert.public_bytes(serialization.Encoding.PEM).decode("utf-8")


def backfill_user_certificates(apps, schema_editor):
    UserProfile = apps.get_model("api", "UserProfile")
    f = _fernet()

    for profile in UserProfile.objects.select_related("user").all():
        existing_cert = (getattr(profile, "certificate", "") or "").strip()
        existing_cert_pem = (getattr(profile, "certificate_pem", "") or "").strip()
        cert_to_check = existing_cert or existing_cert_pem

        needs_regen = False
        if not cert_to_check:
            needs_regen = True
        else:
            try:
                cert_obj = x509.load_pem_x509_certificate(cert_to_check.encode("utf-8"))
                needs_regen = cert_obj.issuer != cert_obj.subject
            except Exception:
                needs_regen = True

        if not needs_regen:
            continue

        encrypted_private = (profile.private_key or "").strip()
        if encrypted_private.startswith("-----BEGIN"):
            private_key_pem = encrypted_private
        else:
            private_key_pem = f.decrypt(encrypted_private.encode("utf-8")).decode("utf-8")

        new_cert_pem = _create_self_signed_user_certificate(
            private_key_pem, profile.user.username
        )
        profile.certificate = new_cert_pem
        # Keep old field in sync for compatibility with older code paths.
        if hasattr(profile, "certificate_pem"):
            profile.certificate_pem = new_cert_pem
        profile.save(update_fields=["certificate", "certificate_pem"])


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_userprofile_certificate_pem"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="certificate",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.RunPython(
            backfill_user_certificates,
            migrations.RunPython.noop,
        ),
    ]

