# Generated by Django 4.2.16 on 2026-05-07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_userprofile_certificate_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="signature_algorithm",
            field=models.CharField(
                choices=[
                    ("RSA-SHA256", "RSA-SHA256"),
                    ("ECDSA-P256-SHA256", "ECDSA-P256-SHA256"),
                ],
                default="RSA-SHA256",
                max_length=32,
            ),
        ),
    ]
