# Generated by Django 4.2.16 on 2026-05-07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_documentrecord_documentversion"),
    ]

    operations = [
        migrations.CreateModel(
            name="SignedDocumentArtifact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("original_filename", models.CharField(blank=True, default="", max_length=255)),
                ("original_bytes", models.BinaryField()),
                ("signature_b64", models.TextField()),
                ("certificate_pem", models.TextField()),
                ("algorithm", models.CharField(max_length=32)),
                ("hash_hex", models.CharField(max_length=64)),
                ("signed_package_json", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "version",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifact",
                        to="api.documentversion",
                    ),
                ),
            ],
        ),
    ]
