# Generated by Django 6.0.2 on 2026-06-02 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_immutability_triggers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="data_hash",
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="documentversion",
            name="chain_hash",
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="documentversion",
            name="payload_hash",
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="documentversion",
            name="record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="versions",
                to="api.documentrecord",
            ),
        ),
        migrations.AlterField(
            model_name="documentversion",
            name="signer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="signed_versions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="signaturelog",
            name="data_hash",
            field=models.CharField(db_index=True, default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="signaturelog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="signature_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
