# Generated by Django 6.0.2 on 2026-06-03 19:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_protect_immutable_fks_and_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentrecord",
            name="verification_token",
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
