# Generated by Django 6.0.2 on 2026-06-03 19:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_documentrecord_verification_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentrecord",
            name="verification_token",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
