# Generated by Django 6.0.2 on 2026-06-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_alter_documentrecord_verification_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "System Administrator"),
                    ("signer", "Cryptographic Signer"),
                    ("auditor", "Forensic Auditor"),
                ],
                default="signer",
                max_length=16,
            ),
        ),
    ]
