# Generated by Django 6.0.2 on 2026-06-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_alter_userprofile_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                ],
                default="APPROVED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("user", "User")],
                default="user",
                max_length=16,
            ),
        ),
    ]
